/*
Error Codes: (First 5 are generated by the .endTransmission() function)
0 - success
1 - length is too long for the buffer
2 - address send, NACK received. Device is not connected.
3 - data send, NACK received
4 - unspecified TWI error occurred.
200 - Cyclic Redundancy Check failed.
201 - You forgot to initialize sensor.
202 - Device got disconnected after being connected
*/


#include <Wire.h>
#include "MS5837.h"
MS5837 sensor;

void setup() {
  Serial.begin(9600);
  Serial.println("Starting");
  Wire.begin();

  // Initialize pressure sensor .init() returns true if successfull.
  while (!sensor.initSensor()) {
    Serial.print("Init failed! Error=");
    Serial.println(sensor.readError());
    delay(5000);
  }  
}

void loop() {
  sensor.requestPressureAndTemp(); //Read the pressure and temperature and stores them internally. 

  Serial.print("Err = ");
  Serial.print(sensor.readError());
  Serial.print("\t");
  Serial.print(sensor.pressure_mbar);
  Serial.print(" mbar\t");
  Serial.print(sensor.pressure_psi);
  Serial.print(" psi\t");
  Serial.print(sensor.getPressure(ATM));
  Serial.println(" atm");

  Serial.print("T = ");
  Serial.print(sensor.temp_c);
  Serial.println(" deg C");

  delay(1000);
}
